// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://timfyefhggsjyiyjhakh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbWZ5ZWZoZ2dzanlpeWpoYWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTMzMTQsImV4cCI6MjA3MjI4OTMxNH0.1q55lwDRRuwdS1nbwNg8mdq-Vgjy3N6hZXmTEt4iQ9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});